spring.application.name=smartbank-api
spring.datasource.url=jdbc:postgresql://localhost:5432/smartbank_db
spring.datasource.username=postgres

spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081