spring.application.name=smartbank-api
spring.datasource.url=jdbc:postgresql://localhost:5432/smartbank_db
spring.datasource.username=postgres
spring.datasource.password=20050320

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081