import { useState } from 'react';
import { send,query,date } from '../api/client';
import { useApi,Heading,Panel,ErrorMessage,Loading,Pagination,StatusBadge,Field,Empty } from '../components/ui';
import type { Page,Notification } from '../types/api';
export default function NotificationsPage() {
  const [page,setPage]=useState(0),[status,setStatus]=useState(''),[event,setEvent]=useState(''),[revision,setRevision]=useState(0),[error,setError]=useState<unknown>(null),[busy,setBusy]=useState<number|null>(null);
  const result=useApi<Page<Notification>>(`/api/notifications?${query({page,status,event})}`,revision);
  async function action(id:number,path:string,method='PUT') {setBusy(id);setError(null);try{await send(`/api/notifications/${id}${path}`,undefined,method);setRevision(r=>r+1);window.dispatchEvent(new Event('notifications-changed'));}catch(e){setError(e);}finally{setBusy(null);}}
  return <><Heading title="Notifications" subtitle="Your banking updates, in one place." icon="/images/page-icons/notifications.png"/><div className="filters"><Field label="Read status"><select value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="">All visible</option><option>UNREAD</option><option>READ</option></select></Field><Field label="Event"><select value={event} onChange={e=>{setEvent(e.target.value);setPage(0);}}><option value="">All events</option>{['TRANSFER_SUCCESS','TRANSFER_RECEIVED','BILL_PAYMENT_SUCCESS','FIXED_DEPOSIT_CREATED','FIXED_DEPOSIT_MATURED','FIXED_DEPOSIT_CLOSED','LOAN_STATUS_CHANGED','CARD_STATUS_CHANGED','SECURITY_ALERT'].map(x=><option key={x}>{x}</option>)}</select></Field></div><ErrorMessage error={error||result.error}/>{result.loading?<Loading/>:result.data&&<Panel>{result.data.content.map(n=><article className={`notification-item ${n.status==='UNREAD'?'unread':''}`} key={n.notificationId}><div><StatusBadge status={n.status}/><small>{date(n.createdAt)}</small><h3>{n.title}</h3><p>{n.message}</p></div><div className="actions"><button className="secondary" disabled={busy===n.notificationId} onClick={()=>action(n.notificationId,n.status==='READ'?'/unread':'/read')}>Mark {n.status==='READ'?'unread':'read'}</button><button className="link-button danger" disabled={busy===n.notificationId} onClick={()=>{if(confirm('Hide this notification?'))action(n.notificationId,'','DELETE');}}>Hide</button></div></article>)}{!result.data.content.length&&<Empty>You’re all caught up.</Empty>}<Pagination data={result.data} onPage={setPage}/></Panel>}</>;
}
