import { Text } from '../i18n';
import { useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { send,query,money,date } from '../api/client';
import { useApi,Heading,Panel,Field,ErrorMessage,Loading,Pagination,StatusBadge,Detail,Empty } from '../components/ui';
import { OtpDialog } from '../components/OtpDialog';
import { ReceiptModal } from '../components/ReceiptModal';
import type { Page,Transaction } from '../types/api';

import { TransactionReportModal } from '../components/TransactionReportModal';

export function TransactionsPage() {
  const [page,setPage]=useState(0),[type,setType]=useState(''),[status,setStatus]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[search,setSearch]=useState('');
  const [selectedTxn, setSelectedTxn] = useState<Transaction | null>(null);
  const [showReportModal, setShowReportModal] = useState(false);
  const {data,error,loading}=useApi<Page<Transaction>>(`/api/transactions?${query({page,type,status,from,to,search})}`);
  return <><Heading title="Transactions" subtitle="A complete view of your account activity." icon="/images/page-icons/history.png" actions={<button type="button" className="button bg-[#c9a227] hover:bg-[#d8af2c] text-black font-bold text-xs px-4 py-2.5 rounded-xl flex items-center gap-1.5 cursor-pointer shadow-md" onClick={() => setShowReportModal(true)}><span>📄</span> Generate Report</button>}/><div className="filters"><Field label="Search"><input value={search} maxLength={200} onChange={e=>{setSearch(e.target.value);setPage(0);}} placeholder="Description"/></Field><Field label="Type"><select value={type} onChange={e=>{setType(e.target.value);setPage(0);}}><option value="">All types</option>{['TRANSFER','BILL_PAYMENT','FD_OPEN','FD_CLOSE'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Status"><select value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="">All statuses</option>{['PENDING','COMPLETED','FAILED','CANCELLED'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="From"><input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(0);}}/></Field><Field label="To"><input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(0);}}/></Field></div><ErrorMessage error={error}/>{loading?<Loading/>:data&&<Panel>{data.content.length?<div className="table-wrap"><table><thead><tr><th><Text value={"Transaction"}/></th><th><Text value={"Type"}/></th><th><Text value={"Date"}/></th><th><Text value={"Amount"}/></th><th><Text value={"Status"}/></th><th>Receipt</th></tr></thead><tbody>{data.content.map(t=><tr key={t.transactionId}><td><Link to={`/app/transactions/${t.transactionId}`}>{t.description}</Link><small>#{t.transactionId}</small></td><td>{t.transactionType.replaceAll('_',' ')}</td><td>{date(t.createdAt)}</td><td>{money(t.amount)}</td><td><StatusBadge status={t.status}/></td><td>{t.status==='COMPLETED'?<button className="button secondary small-btn" onClick={()=>setSelectedTxn(t)}>📄 Receipt</button>:'-'}</td></tr>)}</tbody></table></div>:<Empty>No transactions match your filters.</Empty>}<Pagination data={data} onPage={setPage}/></Panel>}{selectedTxn&&<ReceiptModal transaction={selectedTxn} onClose={()=>setSelectedTxn(null)}/>}{showReportModal&&data&&<TransactionReportModal transactions={data.content} filters={{from,to,type,status,search}} onClose={()=>setShowReportModal(false)}/>}</>;
}

export function TransactionDetailsPage() {
  const {id}=useParams();const [revision,setRevision]=useState(0),[otp,setOtp]=useState(false),[showReceipt,setShowReceipt]=useState(false),[error,setError]=useState<unknown>(null),[busy,setBusy]=useState(false);
  const {data:t,error:loadError,loading}=useApi<Transaction>(`/api/transactions/${id}`,revision);
  async function cancel() {if(!confirm('Cancel this pending request?'))return;setBusy(true);try{await send(`/api/transactions/${id}/cancel`);setRevision(r=>r+1);}catch(e){setError(e);}finally{setBusy(false);}}
  return <><Heading title={`Transaction #${id}`} actions={<Link className="button secondary" to="/app/transactions">All transactions</Link>}/><ErrorMessage error={error||loadError}/>{loading?<Loading/>:t&&<Panel><div className="balance-hero"><span>{t.status==='COMPLETED'?'Transaction confirmation':'Transaction request'}</span><h2>{money(t.amount)}</h2><StatusBadge status={t.status}/></div><div className="details-grid"><Detail label="Type">{t.transactionType.replaceAll('_',' ')}</Detail><Detail label="Description">{t.description}</Detail><Detail label="Requested">{date(t.createdAt)}</Detail><Detail label="Completed">{date(t.completedAt)}</Detail><Detail label="Source account ID">{t.fromAccountId??'Simulated settlement'}</Detail><Detail label="Destination account ID">{t.toAccountId??'Simulated payment/deposit'}</Detail></div>{t.failureCode&&<div className="alert">{t.failureCode.replaceAll('_',' ')}</div>}<div className="actions">{t.canAuthorize&&<><button disabled={busy} onClick={()=>setOtp(true)}>Verify OTP</button><button disabled={busy} className="secondary danger" onClick={cancel}>Cancel request</button></>}{t.status==='COMPLETED'&&<button className="button primary" onClick={()=>setShowReceipt(true)}>📄 Download / Share Receipt</button>}</div></Panel>}{otp&&t&&<OtpDialog id={t.transactionId} onClose={()=>{setOtp(false);setRevision(r=>r+1);}} onComplete={()=>{setOtp(false);setRevision(r=>r+1);setShowReceipt(true);}}/>}{showReceipt&&t&&<ReceiptModal transaction={t} onClose={()=>setShowReceipt(null as any)}/>}</>;
}
